buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://maven.minecraftforge.net/' }
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'com.anatawa12.forge:ForgeGradle:2.3-1.0.+'
        classpath 'gradle.plugin.com.matthewprenger:CurseGradle:1.4.0'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'com.matthewprenger.cursegradle'
apply plugin: 'maven-publish'

version = "v${mod_version}-mc1.12.2"
group = 'git.jbredwards.fluidlogged_api'
archivesBaseName = 'Fluidlogged-API'
sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    version = '1.12.2-14.23.5.2847'
    runDir = 'run'
    mappings = 'stable_39'
    makeObfSourceJar = false
}

repositories {
    maven { url 'https://cursemaven.com' }
    maven { url 'https://maven.daporkchop.net/' }
}

dependencies {
    // optional mod compat
    deobfProvided 'io.github.opencubicchunks:cubicchunks-api:1.12.2-0.0-SNAPSHOT'
    deobfProvided 'curse.maven:astral-sorcery-241721:3044416'
    deobfProvided 'curse.maven:cb-multipart-258426:2755790'
    deobfProvided 'curse.maven:cofh-core-69162:2920433'
    deobfProvided 'curse.maven:dynamic-lights-227874:2563244'
    deobfProvided 'curse.maven:dynamic-surroundings-238891:3497269'
    deobfProvided 'curse.maven:dynamic-trees-252818:3812473'
    deobfProvided 'curse.maven:galacticraft-legacy-564236:4671122'
    deobfProvided 'curse.maven:immersiveengineering-231951:2974106'
    deobfProvided 'curse.maven:industrial-craft-242638:3838713'
    deobfProvided 'curse.maven:mekanism-268560:2835175'
    deobfProvided 'curse.maven:orelib-307806:2820815'
    deobfProvided 'curse.maven:random-things-59816:2905241'
    deobfProvided 'curse.maven:tropicraft-254794:2713918'
    // optional mod compat (dependencies)
    deobfProvided 'curse.maven:codechicken-lib-242818:2779848'
    deobfProvided 'curse.maven:redstone-flux-270789:2920436'
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property 'mod_version', mod_version
    inputs.property 'mcversion', project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        // replace version and mcversion
        expand 'mod_version':mod_version, 'mcversion':project.minecraft.version
    }

    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

task deobfJar(type: Jar) {
    from sourceSets.main.output
    classifier = 'deobf'
}

task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    classifier = 'sources'
}

artifacts {
    archives deobfJar
    archives sourcesJar
}

jar {
    manifest {
        attributes([
                'FMLCorePlugin': 'git.jbredwards.fluidlogged_api.mod.asm.ASMHandler',
                'FMLCorePluginContainsFMLMod': 'true',
                'FMLAT': 'fluidlogged_api_at.cfg'
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
            artifact deobfJar
            artifact sourcesJar
        }
    }
}

//for using asm with intellij
runClient { jvmArgs '-Dfml.coreMods.load=git.jbredwards.fluidlogged_api.mod.asm.ASMHandler' }
runServer { jvmArgs '-Dfml.coreMods.load=git.jbredwards.fluidlogged_api.mod.asm.ASMHandler' }
